import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const c=vm.createContext({performance:{now:()=>0}});vm.runInContext(fs.readFileSync('ext/pilot.js','utf8'),c);const {Pilot,v11Choice}=c.SlpPilot,d=JSON.parse(fs.readFileSync('params.json')),V={...d.defaults,...d.presets.v11_near.values};const old=vm.createContext({performance:{now:()=>0}});vm.runInContext(fs.readFileSync('research/v11_20261001/before/pilot.js','utf8'),old);
for(const key of ['pilotStep','v8Step','v10Step','v10Route','v4Adv'])assert.equal(Pilot.prototype[key].toString(),old.SlpPilot.Pilot.prototype[key].toString());
const base={x:30000,y:30000,ang:0,sp:6.12,sc:1,L:1000,t:10,cmdNow:0,boostNow:false,wall:[30000,30000,20000],segs:[],sid:[],heads:[],hid:[],food:[30200,30000,30],own:[]};
const K={phase:'feed',clearSince:null};assert.equal(v11Choice(K,base,V).phase,'feed');assert.equal(v11Choice(K,{...base,heads:[30260,30000,0,6,1]},V).phase,'feed');assert.equal(v11Choice(K,{...base,t:11,heads:[30240,30000,0,6,1]},V).reason,'near_head');assert.equal(v11Choice(K,{...base,t:12},V).reason,'hold');assert.equal(v11Choice(K,{...base,t:13.01},V).phase,'feed');
const body={...base,segs:[29900,30090,30100,30090,20],sid:[3],t:14};const r=v11Choice(K,body,V);assert.equal(r.reason,'near_body');assert.equal(r.bodyGap,55.5);assert.equal(v11Choice({phase:'feed',clearSince:null},body,{...V,V11_BODY_GAP:0}).phase,'feed');assert.equal(v11Choice({phase:'feed',clearSince:null},{...base,heads:[30050,30000,0,6,1]},{...V,V11_HEAD_R:0}).phase,'feed');
const p=new Pilot(V,'aggressive'),f=new Pilot(p.v101Values(false),'aggressive'),a=new Pilot(p.v101Values(true),'aggressive');let last='';
for(let i=0;i<8;i++){const phase=i>=2&&i<=5?'avoid':'feed';const s={...base,t:20+i*.1,v8Control:{phase,heads:phase==='avoid'?1:0,radius:250,threshold:1,switched:phase!==last?1:0,reason:phase==='avoid'?'near_head':'clear'}};const child=phase==='avoid'?a:f;assert.equal(JSON.stringify(p.step(s)),JSON.stringify(child.step({...s,route:null,threat:null,selectedGuide:null})));assert.equal(p.last.trace.v11_on,1);last=phase;}
fs.writeFileSync('research/v11_20261001/check.json',JSON.stringify({originalFunctionsUnchanged:5,singleNearHead:true,farHeadFeeds:true,bodyGapMeasured:55.5,bodyOnlyAvoid:true,disabledConditions:true,clearHoldReturn:true,controllerParityFrames:8,realSurvivalTest:false},null,2));console.log('V11 checks passed');
