import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const ctx=vm.createContext({performance:{now:()=>0}});vm.runInContext(fs.readFileSync('ext/pilot.js','utf8'),ctx);const {Pilot,v8Choice}=ctx.SlpPilot,d=JSON.parse(fs.readFileSync('params.json')),V={...d.defaults,...d.presets.v101_hybrid.values};
const old=vm.createContext({performance:{now:()=>0}});vm.runInContext(fs.readFileSync('research/v101_20261001/before/pilot.js','utf8'),old);
for(const key of ['pilotStep','v8Step','v10Step','v10Route','v4Adv'])assert.equal(Pilot.prototype[key].toString(),old.SlpPilot.Pilot.prototype[key].toString(),key+' unchanged');assert.equal(v8Choice.toString(),old.SlpPilot.v8Choice.toString());
const a={phase:'feed',clearSince:null},b={phase:'feed',clearSince:null};for(const [t,heads,body] of [[1,0,0],[2,3,0],[3,0,0],[3.5,0,0],[4.1,0,0],[5,0,20],[6,0,0],[7.1,0,0]])assert.equal(JSON.stringify(v8Choice(a,heads,t,V,body)),JSON.stringify(old.SlpPilot.v8Choice(b,heads,t,V,body)));
const p=new Pilot(V,'aggressive'),feed=new Pilot(p.v101Values(false),'aggressive'),avoid=new Pilot(p.v101Values(true),'aggressive');const base={x:30000,y:30000,ang:0,sp:6.12,sc:1,L:1000,t:10,cmdNow:0,boostNow:false,wall:[30000,30000,20000],segs:[],sid:[],heads:[],hid:[],food:[30200,30000,30],own:[]};
let last='';for(let i=0;i<8;i++){const phase=i<2||i>5?'feed':'avoid';const state={...base,t:10+i*.1,v8Control:{phase,heads:phase==='avoid'?3:0,threshold:3,radius:450,switched:phase!==last?1:0,bodyDensity:0}};const child=phase==='feed'?feed:avoid;const r=p.step(state),q=child.step({...state,route:null,selectedGuide:null,threat:null});assert.equal(JSON.stringify(r),JSON.stringify(q));assert.equal(p.last.trace.mode,child.last.trace.mode);assert.equal(p.last.trace.v8_phase,phase);last=phase;}
assert(p.v101Feed&&p.v101Avoid);assert.equal(p.v101Feed.values.V10_ON,0);assert.equal(p.v101Avoid.values.V10_ON,1);p.setParams({...V,W_FOOD:8},'aggressive');assert.equal(p.v101Feed.values.W_FOOD,8);assert.equal(p.v101Avoid.values.W_FOOD,8);
fs.writeFileSync('research/v101_20261001/check.json',JSON.stringify({originalFunctionsUnchanged:6,switchParity:true,controllerParityFrames:8,persistentChildren:true,paramUpdate:true,liveSurvivalTest:false},null,2));console.log('hybrid parity checks passed');
