import json,gzip,sys,math,statistics,hashlib,base64
from pathlib import Path
p=Path(sys.argv[1]);read=lambda n:json.loads(gzip.decompress((p/n).read_bytes()) if n.endswith('.gz') else (p/n).read_text())
rec=read('slp_01.json');log=read('slp_01_log.json.gz');box=read('slp_01_box.json.gz');rows=[dict(zip(log['keys'],r)) for r in log['log']];route=[r for r in rows if r.get('mode')=='v10route'];end=rows[-1]['t'];tail=[r for r in rows if r['t']>=end-3]
def pct(v):
 v=sorted(x for x in v if isinstance(x,(int,float)) and math.isfinite(x));return {'p50':v[len(v)//2],'p95':v[min(len(v)-1,int(len(v)*.95))],'max':v[-1]} if v else None
cams=[json.loads(x) for x in (p/'game_01_camera.jsonl').read_text().splitlines()];intervals=[b['t']-a['t'] for a,b in zip(cams,cams[1:])]
from collections import Counter
result={'build':rec['ext'],'seconds':rec['seconds'],'L_max':rec['L_max'],'server':rec.get('server'),'players':rec.get('players'),'capped':rec.get('capped',False),'decision_errors':rec['errors'],'page_errors':(p/'page_errors.jsonl').read_text() if (p/'page_errors.jsonl').exists() else [],'modes':dict(Counter(r.get('mode') for r in rows)),'rows':len(rows),'route_rows':len(route),'route_frame_percent':round(100*len(route)/max(1,len(rows)),1),'routes_3_rows':sum(r.get('v10_routes',0)>=3 for r in rows),'long_remaining_over_4_2s_rows':sum((r.get('v10_continuation_s') or 0)>4.2 for r in rows),'remaining_seconds':pct([r.get('v10_continuation_s') for r in route]),'closure_risk':pct([r.get('v10_closure_risk') for r in route]),'closure_cert_rows':sum(bool(r.get('v10_closure_cert')) for r in route),'decision_ms':rec.get('decide_ms'),'observation_to_command_ms':rec.get('obs_to_cmd_ms'),'route_map_ms':pct([r.get('v10_map_ms') for r in rows]),'rejects':dict(Counter(str(r.get('v10_reject')) for r in rows)),'last3s_modes':dict(Counter(r.get('mode') for r in tail)),'last3s':[{k:r.get(k) for k in ['t','mode','cmd','boost','v10_routes','v10_reject','v10_root_safe','v10_clear','v10_closure_risk']} for r in tail],'screenshots':len(cams),'capture_interval_s':pct(intervals),'capture_error':(p/'game_01_camera_error.txt').read_text() if (p/'game_01_camera_error.txt').exists() else None,'settings_changes':rec.get('changes'),'hashes':{x.name:hashlib.sha256(x.read_bytes()).hexdigest() for x in p.glob('slp_01*')},'limits':['Single live game verifies observed operation, not survival improvement.','Route frame share is not independent escape success rate.','Closure index is not calibrated probability.','Nearest observed body is not confirmed server killer.']}
(p/'validation.json').write_text(json.dumps(result,ensure_ascii=False,indent=2))
items=[]
for c in cams[-18:]:items.append({'t':c['t'],'src':'data:image/jpeg;base64,'+base64.b64encode((p/c['file']).read_bytes()).decode()})
html='''<!doctype html><html lang="ko"><meta charset="utf-8"><title>V10 실게임 검증</title><style>body{background:#101722;color:#e4eaf4;font:15px system-ui;margin:20px}h1{font-size:23px}img{max-width:100%;max-height:78vh;display:block;margin:15px auto}button{padding:9px;background:#273d57;color:white;border:0}input{width:60%}p{color:#b8cadd}</style><h1>V10 실게임 1판 · 마지막 화면</h1><p>SUMMARY</p><button id="prev">이전</button> <input id="pos" type="range" min="0"> <button id="next">다음</button> <span id="time"></span><img id="frame"><p>촬영 시작 기준 시각입니다. 판단 로그의 게임 시간과 기준이 다릅니다.</p><script>const frames=FRAMES;const p=document.getElementById('pos');p.max=frames.length-1;p.value=Math.max(0,frames.length-5);function draw(){let f=frames[+p.value];document.getElementById('frame').src=f.src;document.getElementById('time').textContent=f.t.toFixed(3)+'초'}p.oninput=draw;document.getElementById('prev').onclick=()=>{p.value=Math.max(0,+p.value-1);draw()};document.getElementById('next').onclick=()=>{p.value=Math.min(frames.length-1,+p.value+1);draw()};draw();</script></html>'''
summary=f"빌드 {rec['ext']} · {rec['seconds']:.1f}초 · 최대 길이 {rec['L_max']} · 경로 추종 판단 {result['route_frame_percent']}% · 판단 오류 {rec['errors']} · {'시간 상한 종료' if rec.get('capped') else '사망 종료'}"
(p/'live_viewer.html').write_text(html.replace('SUMMARY',summary).replace('FRAMES',json.dumps(items)))
(p/'validation_source.txt').write_text('V10 긴 경로 실게임 검증 — 결과 원문\n원본 '+str(p)+'\n'+json.dumps(result,ensure_ascii=False,indent=2))
print(json.dumps({k:v for k,v in result.items() if k not in ['last3s','hashes']},ensure_ascii=False,indent=2))
