import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {performance} from 'node:perf_hooks';
const c=vm.createContext({performance});vm.runInContext(fs.readFileSync('ext/pilot.js','utf8'),c);
const H=c.SlpPilot, cfg=JSON.parse(fs.readFileSync('params.json'));
const V={...cfg.defaults,...cfg.presets.v81_density.values};
const density=(segs,r=450)=>H.bodyDensity({x:0,y:0,segs},r);
const line=[-1000,100,1000,100,70], d=density(line);
assert(d>=18 && d<25);assert.equal(density([]),0);
assert.equal(density([-1000,800,1000,800,20]),0);
assert.equal(density([...line,...line]),d);
assert.equal(density([-1000,100,0,100,70,0,100,1000,100,70]),d);
assert(density([-1000,100,1000,100,20])<d);
assert.equal(density([0,0,0,0,1000]),100);
assert.equal(density(line,0),0);assert.equal(density([NaN,0,0,0,20]),0);
const K={phase:'feed',clearSince:null};
assert.equal(H.v8Choice(K,0,0,V,d).reason,'body');
assert.equal(H.v8Choice(K,0,.1,V,0).reason,'hold');
assert.equal(H.v8Choice(K,3,.9,V,0).reason,'heads');
assert.equal(H.v8Choice(K,0,1,V,0).phase,'avoid');
assert.equal(H.v8Choice(K,0,1.99,V,0).phase,'avoid');
assert.equal(H.v8Choice(K,0,2.01,V,0).phase,'feed');
assert.equal(H.v8Choice(K,3,3,V,d).reason,'heads+body');
assert.equal(H.v8Choice({phase:'feed',clearSince:null},0,0,{...V,V81_BODY_ON:0},100).phase,'feed');
assert.equal(H.v8Choice({phase:'feed',clearSince:null},0,0,{...V,V81_BODY_PCT:d},d).phase,'avoid');
// Evaluate the actual page observer, including enemy filtering and independent observation range.
const mod=fs.readFileSync('ext/mod.js','utf8');
const src=mod.slice(mod.indexOf('function observe() {'),mod.indexOf('\nfunction snakeLen'));
const me={id:-1,xx:0,yy:0,ang:0,sp:6,sc:1,pts:[]};
const enemy=(id=2)=>({id,xx:2000,yy:100,ang:0,sp:6,sc:70/14.5,pts:[{xx:-2000,yy:100}]});
function observe(enemies,values=V){return vm.runInNewContext(`(${src})()`,{window:{SlpPilot:H,slither:me,slithers:[me,...enemies],playing:true,foods:[],foods_c:0,grd:0,flux_grd:20000},S:{values},performance:{now:()=>1000},v8Switch:{phase:'feed',clearSince:null},RADIUS:1150,FOOD_RADIUS:3000,sent:{ang:0},snakeLen:()=>100,route:null,planVer:0,planSentAt:0});}
const o=observe([enemy()]);assert.equal(o.v8Control.heads,0);assert.equal(o.v8Control.reason,'body');assert.equal(o.v8Control.bodyDensity,d);
assert.equal(observe([{...enemy(),dead:true}]).v8Control.bodyDensity,0);
assert.equal(observe([enemy(-1)]).v8Control.bodyDensity,0);
assert.equal(observe([{...enemy(),pts:[{xx:-2000,yy:100},{xx:0,yy:100,dying:true}]}]).v8Control.bodyDensity,0);
assert.equal(observe([{...enemy(),pts:[]}]).v8Control.bodyDensity,0);
assert.equal(observe([enemy()],{...V,V81_BODY_R:100}).v8Control.bodyTrigger,1);
assert.equal(observe([enemy()],{...V,V81_BODY_R:2000}).v8Control.bodyTrigger,0);
assert.equal(observe([enemy()],{...V,V81_BODY_ON:0}).v8Control.phase,'feed');
const many=Array.from({length:100},(_,i)=>[-500,i*10-500,500,i*10-500,10]).flat();
const times=[];for(let i=0;i<100;i++){const t=performance.now();density(many);times.push(performance.now()-t);}times.sort((a,b)=>a-b);
const result={geometry:true,overlapAndSubdivisionInvariant:true,crossingSegment:true,headlessBodyTrigger:d,ownDeadDyingExcluded:true,orAndReleaseTimer:true,radiusAndThreshold:true,bodyDensity100SegmentsMs:{p50:times[50],p95:times[95]},scope:'synthetic trigger correctness, not survival'};
fs.writeFileSync('research/v81_density_20260930/verify.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
