import json,hashlib,time
from pathlib import Path
root=Path(__file__).resolve().parents[2];here=root/'research/t4_fixed_20261002'
run=root/'runs/t4_20261002_122618'
summary=json.loads((run/'summary.json').read_text())
old=json.loads((root/'runs/t4_20261002_121802/summary.json').read_text())
checks={name:json.loads((here/name).read_text()) for name in ['check.json','selection_check.json','mock.json','curve_check.json','hashes.json']}
new=summary['games'];aggregate={'run':str(run.relative_to(root)),'build':summary.get('build'),'games':len(new),'ended':summary.get('ended'),'completed':summary.get('completed'),'near_seconds':sum(g['near_seconds'] for g in new),'pass_games':sum(g['longest_near_seconds']>=3 and not g['errors'] for g in new),'success':len(new)==5 and sum(g['longest_near_seconds']>=3 and not g['errors'] for g in new)>=2 and not summary.get('page_errors') and not summary.get('error'),'page_errors':summary.get('page_errors'),'error':summary.get('error')}
(here/'result.json').write_text(json.dumps(aggregate,ensure_ascii=False,indent=2))
text="# T4 user-selected fixed -5px follower and nearest-long selection — original evidence\n\nUser original direct instruction: 내가 정해줄께, -5를 안전 오프셋으로 설정하고. 가장 딱 붙어서 따라가는 모델로 새로 만들어서 테스트를해봐\nUser latest direct steering: 대상 선정을 1000이상이면 그냥 가까운것을 선정하는것이 낫지 않을까? 그보다 긴 적이 나오면 그쪽으로 옮기고.\nThe user-selected -5px setting is an experiment choice, not a universally measured safe collision offset. The implementation interprets 1000 under the existing observed body-length metric in world pixels, not game score L. This interpretation was communicated during work.\n\nImplementation: independent T4; nearest eligible connected observed body with total visible length>=1000px. Other old controller methods preserved. Switch to nearest candidate with visible length>current*1.05 after current target age>=2s and candidate persists>=0.5s; 0.7s actual-turn motion guard must permit a move toward candidate. The 5%, 2s, and 0.5s choices are implementation hysteresis, not user numeric quotas. Curvature/runway/reachable observation limits still apply. A partial observed length can change with occlusion and is not the opponent's whole length. The guard is a model forecast, not a live survival guarantee.\n\nFixed goal -5px. Continuous approach after alignment, no 15-sample gate to approach, raw frames and all deaths retained. Selected local body guard applies the goal once. Other bodies/head/wall interference logged. Catch-up/fast-opponent boost enabled; actual command history and speed are retained.\n\nPrior T3 continuation stopped and preserved for this explicitly requested new model/test: research/t4_fixed_20261002/replaced_t3.json, runs/t3_20261002_120229. Prior T4 run had 3 deaths +1 user-stop record, interrupted for latest selection change, not five completed games. Live builds are separated in the report and raw records.\n\nValidation criterion selected by implementation: 5-game batch, 120s cap/game; at least two independent games with same-target gap within goal±2px and heading<15deg continuously >=3s, no judgement/page errors. This is tracking validation, not universal offset certification. Previous curve checks cover build1002-317482f8; latest selector and straight delayed quantized checks cover current production build. The synthetic local motion model does not establish the actual server collision boundary.\n\n"
text+='## Final aggregation from frozen raw run records\n\n```json\n'+json.dumps(aggregate,ensure_ascii=False,indent=2)+'\n```\n'
text+='## Current raw summary and recorded live game analyses\n\n```json\n'+json.dumps(summary,ensure_ascii=False,indent=2)+'\n```\n'
text+='## Prior T4 batch summary — different build, interrupted\n\n```json\n'+json.dumps(old,ensure_ascii=False,indent=2)+'\n```\n'
text+='## Verification outputs and current hashes\n\n```json\n'+json.dumps(checks,ensure_ascii=False,indent=2)+'\n```\n'
text+='## Original inventory\n\n'+ '\n'.join(str(p.relative_to(root)) for p in sorted(run.glob('*')) if p.is_file())+'\n'
text+='## Exact production method\n\n```js\n'+(here/'method.js').read_text()+'\n```\n'
(here/'evidence.md').write_text(text)
print(json.dumps(aggregate,ensure_ascii=False))
