from pathlib import Path
p=Path('ext/mod.js');s=p.read_text()
def sub(a,b):
 global s
 assert a in s,a[:100];s=s.replace(a,b)
sub('const BASIC = [',"const BASIC = [['v9Map', 'V9 몸통 벽 지도'], ['v9Routes', 'V9 탈출 후보'], ")
sub("m.kind === 'v8' ? pilot.v8Route", "m.kind === 'v9' ? pilot.v9Route(m.s, m.ver) : m.kind === 'v8' ? pilot.v8Route")
sub('draw: {chosen: d.chosen, mazePath:', 'draw: {v9Paths: d.v9Paths, v9Walls: d.v9Walls, v9Map: d.v9Map, v9Reason: d.v9Reason, chosen: d.chosen, mazePath:')
sub('route = r.pts ? {algo:', "route = (r.pts || r.algo === 'v9') ? {routes: r.routes, map: r.map, algo:")
sub('if (S.values.V8_ON) {\n    const seen', 'if (!S.values.V9_ON && S.values.V8_ON) {\n    const seen')
sub('const seven = !S.values.V8_ON', 'const nine = !!S.values.V9_ON;\n  const seven = !nine && !S.values.V8_ON')
sub('const six = S.values.V8_ON ?', 'const six = nine ? false : S.values.V8_ON ?')
sub('Math.max(RADIUS, six ?', 'Math.max(RADIUS, nine ? S.values.V9_OBS : 0, six ?')
sub('if (P[i].dying) continue; x = P[i].xx; y = P[i].yy;', 'if (P[i].dying) { if (nine) { px = null; py = null; pin = false; } continue; } x = P[i].xx; y = P[i].yy;')
sub('const inn = inr(x, y);', 'if (nine && !Number.isFinite(x + y)) { px = null; py = null; pin = false; continue; }\n      const inn = inr(x, y);')
sub('if (px !== null && (inn || pin))', 'if (px !== null && (inn || pin || (nine && Math.min(px,x)-r <= hx+radius && Math.max(px,x)+r >= hx-radius && Math.min(py,y)-r <= hy+radius && Math.max(py,y)+r >= hy-radius)))')
sub('if (S.values.V4_ON || S.values.V6_ON || S.values.V7_ON || S.values.V8_ON)', 'if (S.values.V9_ON || S.values.V4_ON || S.values.V6_ON || S.values.V7_ON || S.values.V8_ON)')
sub('const v8 = !!S.values.V8_ON, v7 = !v8', 'const v9 = !!S.values.V9_ON, v8 = !v9 && !!S.values.V8_ON, v7 = !v9 && !v8')
sub('every = v6 ?', 'every = v9 ? (S.values.V9_PLAN_MS || 300) : v6 ?')
sub('const needPlan = v8 ?', 'const needPlan = v9 ? true : v8 ?')
sub("kind: v8 ? 'v8'", "kind: v9 ? 'v9' : v8 ? 'v8'")
sub('(S.values.V8_ON || S.values.V7_ON || S.values.V6_ON)', '(S.values.V9_ON || S.values.V8_ON || S.values.V7_ON || S.values.V6_ON)')
sub('function setValue(k, v) {\n', 'function setValue(k, v) {\n  if (v && /^V(?:2|3|4|41|5|6|7|8)_ON$/.test(k)) S.values.V9_ON = 0;\n')
sub('`${S.values.V8_ON ?', "`${S.values.V9_ON ? 'V9 · 다중 탈출' : S.values.V8_ON ?")
sub('v6 = !v8 && !v7', 'v6 = !v9 && !v8 && !v7')
for token in ['v41','v5','v4','v2']:sub(token+' = !v8', token+' = !v9 && !v8')
sub("btn('V1', !v8", "btn('V1', !v9 && !v8")
sub("() => { setValue('V8_ON', 0);", "() => { setValue('V9_ON', 0); setValue('V8_ON', 0);")
sub("반경·점유율 조정 가능'));", "반경·점유율 조정 가능'),\n      btn('V9', v9, () => applyPreset('v9_maze'), '적 몸통을 벽으로 지도화하고 실제 회전 가능한 다중 탈출 궤적을 탐색·추종'));")
sub('const rows = v8', "const rows = v9\n      ? [sw('V9_OBS', '미로 지도 반경', '현재 관측된 몸통을 벽으로 만드는 범위', '🗺'), sw('V9_EDGE', '탈출 목표 거리', '지도 안 탐색 경계까지의 목표. 지도 반경보다 80px 이상 작게 제한', '↗'), sw('V9_MARGIN', '몸통·벽 여유', '내 두께와 적 두께에 더할 여유 (px)', '↔'), sw('V9_ROUTES', '탈출 후보 수', '서로 다른 출구 방향의 통과 검증 경로만 표시', '⑶'), sw('V9_H', '미로 탐색 시간', '실제 회전·속도로 탐색할 최대 시간 (s)', '⏱'), sw('V9_HEAD_PAD', '적 머리 예측 여유', '적의 현재 진행 예측에 더하는 불확실성 여유', '🛡')]\n      : v8")
sub('ms: last.ms, mode: last.trace.mode,', 'ms: last.ms, mode: last.trace.mode, v9_routes: last.trace.v9_routes, v9_reason: last.trace.v9_reason,')
# Keep V9's physical heading tracker active even if an old saved TRACK_ON was off.
sub('if (S.values.TRACK_ON && r.plan', 'if ((S.values.V9_ON || S.values.TRACK_ON) && r.plan')
sub('if (S.values.TRACK_MODE) {', 'if (S.values.V9_ON || S.values.TRACK_MODE) {')
sub('if (S.values.TRACK_ON) { hookSocket(); track(); }', 'if (S.values.V9_ON || S.values.TRACK_ON) { hookSocket(); track(); }')
# Record V9 facts in the existing tabular log too.
sub("'v81_reason'", "'v81_reason', 'v9_routes', 'v9_reason', 'v9_clear', 'v9_plan_ms'")
sub('tr.v81_reason]);', 'tr.v81_reason, tr.v9_routes, tr.v9_reason, tr.v9_clear, tr.v9_plan_ms]);')
p.write_text(s)
