import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';import zlib from 'node:zlib';
const load=path=>{const c=vm.createContext({performance});vm.runInContext(fs.readFileSync(path,'utf8'),c);return c.SlpPilot;};
const api=load('ext/pilot.js'),old=load('research/t6_escape_20261002/before/pilot.js'),D=JSON.parse(fs.readFileSync('params.json')),V={...D.defaults,...D.presets.t6_escape.values};
const names=['t5Step','t4Step','t3Step','t2Step','t1Step','pilotStep','v10Step','v111Step','va1Step','v4Adv','v9World','v9Roll','v9Root'];for(const n of names)assert.equal(api.Pilot.prototype[n].toString(),old.Pilot.prototype[n].toString(),n);assert.equal(api.t5Contours.toString(),old.t5Contours.toString());
const make=(parts=[],heads=[])=>({x:30000,y:30000,ang:0,sp:5.8,sc:1,t:0,L:1000,wall:[30000,30000,20000],cmdNow:0,boostNow:false,segs:parts.flatMap(p=>[30000+p[0],30000+p[1],30000+p[2],30000+p[3],p[4]??20]),sid:parts.map((p,i)=>p[5]??i+1),heads:heads.flatMap(h=>[30000+h[0],30000+h[1],h[2],h[3]??5.8,h[4]??1]),hid:heads.map((_,i)=>100+i),food:[],own:[]});
const curve=[];for(let k=0;k<96;k++){const a=k*Math.PI/48,b=(k+1)*Math.PI/48;if(Math.abs((a+b)/2-Math.PI/2)<.22)continue;curve.push([300*Math.cos(a),300*Math.sin(a),300*Math.cos(b),300*Math.sin(b),20,9]);}
const p=new api.Pilot(V),s=make(curve),ph=p.v4Physics(1),history=[{t:-2,ang:0,boost:false}],rows=[];
for(let k=0;k<70;k++){s.cmdHistory=history.slice();s.cmdNow=history.at(-1).ang;s.boostNow=history.at(-1).boost;const [cmd,boost]=p.step(s);if(k%4===0)rows.push({t:s.t,x:s.x-30000,y:s.y-30000,h:s.ang,cmd,boost,...p.last.trace,path:p.last.draw.t6Path.map((v,i)=>v-30000),guides:p.last.draw.t6Guides.map(P=>P.map(v=>v-30000))});
for(let j=0;j<4;j++){const t=s.t+j*.025,q=history.findLast(q=>q.t<=t-V.TRACK_LAT)||history[0],n=p.v4Adv({x:s.x,y:s.y,h:s.ang,v:s.sp*31},q.ang,q.boost,.025,ph);s.x=n.x;s.y=n.y;s.ang=n.h;s.sp=n.v/31;}history.push({t:s.t,ang:cmd,boost});s.t+=.1;}
fs.writeFileSync('research/t6_escape_20261002/curve_debug.json',JSON.stringify(rows,null,2));console.log(rows.map(r=>({t:r.t,x:r.x,y:r.y,cmd:r.cmd,boost:r.boost,routes:r.t6_routes,reason:r.t6_graph_reason,phase:r.t6_phase,depth:r.t6_depth})));