import fs from 'node:fs';import vm from 'node:vm';vm.runInThisContext(fs.readFileSync(process.argv[2],'utf8'));const D=JSON.parse(fs.readFileSync('params.json')),V={...D.defaults,...D.presets.v10_layered.values,V10_BUDGET:90,V10_FOOD_RISK:100,V10_FOOD_W:2,V9_CENTER_W:0};
const scenarios=[{name:'crossing',x:250,y:-250,h:Math.PI/2,v:210},{name:'crossing_boost',x:250,y:-400,h:Math.PI/2,v:400},{name:'wrap',x:0,y:-300,h:0,v:190},{name:'pursuit',x:-250,y:130,h:0,v:240}];const results=[];
function distance(ax,ay,bx,by){const dx=bx-ax,dy=by-ay,u=Math.max(0,Math.min(1,-(ax*dx+ay*dy)/(dx*dx+dy*dy||1)));return Math.hypot(ax+u*dx,ay+u*dy)}
for(const c of scenarios){const p=new SlpPilot.Pilot(V,'safe'),mapper=new SlpPilot.Pilot(V,'safe'),threatPilot=new SlpPilot.Pilot(V,'safe'),ph=p.v4Physics(1),dt=1/30;let st={x:30000,y:30000,h:0,v:ph.cs},enemy={x:30000+c.x,y:30000+c.y,h:c.h,v:c.v},trail=[];
for(let i=0;i<120;i++){let d=i*5;if(c.name==='wrap'){let a=-Math.PI/2-d/300;trail.push({x:30000+300*Math.cos(a),y:30000+300*Math.sin(a)});}else trail.push({x:enemy.x-Math.cos(enemy.h)*d,y:enemy.y-Math.sin(enemy.h)*d});}
let s={t:1,sc:1,L:1000,wall:[30000,30000,20000],own:[],food:[30500,30000,80,30800,30200,80]},route=null,selected=null,cmd=0,boost=false,history=[{t:0,ang:0,boost:false}],trace=[],ver=0,dead=false,eaten=0;
for(let i=0;i<600;i++){let segs=[],sid=[];for(let j=1;j<trail.length;j++){segs.push(trail[j-1].x,trail[j-1].y,trail[j].x,trail[j].y,14.5);sid.push(1);}s={...s,x:st.x,y:st.y,ang:st.h,sp:st.v/31,t:1+i*dt,cmdNow:cmd,boostNow:boost,cmdHistory:history.slice(-30),route,segs,sid,heads:[enemy.x,enemy.y,enemy.h,enemy.v/31,1],hid:[1]};s.threat=threatPilot.v10Threat(s,i);if(i%10===0){route=mapper.v10Route({...s,selectedGuide:selected},++ver);s.route=route;}
[cmd,boost]=p.step(s);selected=p.last.selectedGuide??null;history.push({t:s.t,ang:cmd,boost});let active=history[0];for(const q of history){if(q.t>s.t-(V.TRACK_LAT??.06))break;active=q;}const next=p.v4Adv(st,active.ang,active.boost,dt,ph),W=p.v10World(s);
let h=enemy.h;if(c.name==='wrap')h+=enemy.v/300*dt;if(c.name==='pursuit'){const target=Math.atan2(st.y-enemy.y,st.x-enemy.x),diff=Math.atan2(Math.sin(target-h),Math.cos(target-h));h+=Math.max(-ph.w*dt,Math.min(ph.w*dt,diff));}const en={...enemy,x:enemy.x+Math.cos(h)*enemy.v*dt,y:enemy.y+Math.sin(h)*enemy.v*dt,h};
if(W.check(st,next,0,0,0,false)<0||distance(st.x-enemy.x,st.y-enemy.y,next.x-en.x,next.y-en.y)<29){dead=true;trace.push({t:s.t,x:next.x,y:next.y,mode:'collision'});break;}
st=next;enemy=en;trail.unshift({x:enemy.x,y:enemy.y});while(trail.length>140)trail.pop();let food=[];for(let k=0;k<s.food.length;k+=3){if(Math.hypot(st.x-s.food[k],st.y-s.food[k+1])<21)eaten++;else food.push(...s.food.slice(k,k+3));}s.food=food;trace.push({t:s.t,x:st.x,y:st.y,mode:p.last.trace.mode,id:p.last.trace.v10_route_id});}
results.push({name:c.name,dead,seconds:trace.length/30,eaten,routeFraction:trace.filter(x=>x.mode==='v10route').length/trace.length,trace});}
fs.writeFileSync(process.argv[3],JSON.stringify(results));console.log(results.map(({trace,...r})=>r));
