from pathlib import Path
import json,hashlib
P=Path('research/v10_maze_2h_20261001');d=json.load(open(P/'final_summary.json'))
lines=['# V10 two-hour improvement — source, verification and live results','', 'Timebox: 2026-10-01 13:26:44–15:26:44 KST.','Status: '+d['status']+'. Current build '+d['build']+'.','', 'User requirements (facts about requests, not verified performance): prioritize missing maze escape at 73F; show multiple routes; hold selected path below risk threshold; improve food collection; repeat live tests for two hours. Later user requested proactive boost for crowded escape and straight food approaches, then an adjustable consumption cost. Default0 was chosen by the assistant to match this request; it is not an empirically optimized setting.','', '## Verified implementation scope','- Independent 32px topological exit search, followed by executable turning/speed/continuous collision checks; entry manoeuvre can join a corridor behind current turning circle. Static guide and time-checked prefix are distinct.','- Hold selected route below V10_SWITCH_RISK; invalid/completed paths may change immediately. All accepted candidates carry numbered RISK labels. RISK is a heuristic index, not probability.','- Pellet approach continuously re-aims, verifies return to escape corridor, and preserves local target. Food waypoint requires continuing exit. Center preference is attenuated when food exists.','- V10 observed-command response lag changed 0.17→0.06 s after held-out fits on two runs. This is not server RTT.','- Current enemy target heading is recorded from client wang, predicted until reached, then straight. Future heading changes remain unknown; uncertainty padding retained.','- Final boost change: existing wrap/corridor/intercept classifications remove boost consumption penalty during escape; same-corridor faster boost is preferred only after passing path checks and no material increase (>0.02) in closure index. Food approach compares arrival time and retains existing mass/distance/alignment gates.','', '- Adjustable V10_BOOST_COST slider: default0, range0–1. Normal/food boost penalty changes with this setting; wrap/corridor/intercept escape remains exempt, explicitly stated in UI. Local0/1 test and browser change-persist-restore are separately recorded.','', '## Live records (sequential, not matched A/B)','|cycle|build|page seconds|end|max length|route decision %|errors|','|---|---|---:|---|---:|---:|---:|']
for r in d['runs']:lines.append(f"|{r['cycle']}|{r['build']}|{r['seconds']}|{'time cap, not death' if r['capped'] else 'death'}|{r['L_max']}|{r['route_pct']}|{r['errors']}|")
lines+=['','## Explicit limits','- Cycle14, if present, is a 45-second final-slider connection smoke test, not a survival trial.','- Original 33F/73F full state was not retained; synthetic 73F topology sketch is not exact replay. No claim that the original death would have been prevented.','- All successful local tests are model checks. Real deaths remain. Sequential lengths/route fractions do not establish causal survival improvement.','- A 90ms budget can leave fewer candidates or fail same-exit repair; 500ms structural checks are separate. Experimental preferred-first repair was not adopted because repeated timing-sensitive results were inconclusive.','- Cycle9 forecast-shortening experiment was not adopted; full 1.2s dynamic prefix restored.','- Page time and wall clock differ. Capped games are not counted as deaths.','', '## Local validation and matched prediction outputs']
for fn in ['contracts_structural.json','boost_contract_before.json','boost_contract_after.json','head_target_contract.json','preferred_decision.json','cost_zero.json','cost_one.json','cost_ui_result.json']:
 f=P/fn
 if f.exists():lines+=['### '+fn,'```json',f.read_text(),'```']
for n in [11,12,13]:
 pp=sorted(Path('runs').glob(f'v10_maze_cycle{n}_*'))
 if pp and (pp[-1]/'head_target_errors.json').exists():lines+=['### '+str(pp[-1]/'head_target_errors.json'),'```json',(pp[-1]/'head_target_errors.json').read_text(),'```']
lines+=['','## Raw provenance','```json',json.dumps({'current_hashes':{f:hashlib.sha256(Path(f).read_bytes()).hexdigest()for f in ['ext/pilot.js','ext/mod.js','params.json','ext/params.js','ext/manifest.json']},'runs':d['runs']},ensure_ascii=False,indent=2),'```']
(P/'final_source.txt').write_text('\n'.join(lines))
print(P/'final_source.txt')
