from pathlib import Path
import json,hashlib
p=Path('research/v10_maze_2h_20261001');runs=[]
for n in range(1,10):
 a=sorted(Path('runs').glob(f'v10_maze_cycle{n}_*'))
 if not a:continue
 r=a[-1];d=json.loads((r/'summary.json').read_text());rec=json.loads((r/'slp_01.json').read_text());runs.append({'cycle':n,'run':str(r),'build':rec['ext'],'game':d['games'][0], 'raw_hashes':{x.name:hashlib.sha256(x.read_bytes()).hexdigest() for x in r.glob('slp_01*')}})
fits={}
for n in [7,8]:
 r=Path(runs[n-1]['run']);fits[str(n)]={'fit':json.loads((r/'turn_delay_fit.json').read_text()),'heldout_kinematics':json.loads((p/f'cycle{n}_kinematics_result.json').read_text())}
data={'status':'in_progress; 2-hour session ends 2026-10-01 15:26:44 KST','current_build':json.loads(Path('ext/manifest.json').read_text())['version_name'],'current_hashes':{f:hashlib.sha256(Path(f).read_bytes()).hexdigest() for f in ['ext/pilot.js','ext/mod.js','params.json']},'changes_after_cycle4':['Cycle5 food waypoint with continuing escape; cycle6 keeps food search from starving first exit and evaluates purposeful boost','Cycle7 local pellet target hold and physically verified entry manoeuvre before joining escape route','Cycle8 re-aims toward pellets along the curved approach and verifies return to selected corridor; risk penalty and displayed path updated for detour','Cycle9 experimental forecast hard-gate shortening was tested once and not adopted; restored cycle8 1.2-second hard forecast for cycle10','Cycle10 changes V10 preset TRACK_LAT and current setting from 0.17 to 0.06 based on held-out kinematics; other current user settings preserved'],'runs':runs,'kinematics':fits,'synthetic_food':{'before':[{k:v for k,v in x.items() if k!='trace'} for x in json.loads((p/'newfood_before.json').read_text())],'after':[{k:v for k,v in x.items() if k!='trace'} for x in json.loads((p/'newfood_pursuit.json').read_text())],'parameters_at_generation':'cycle7_code/params.json; 0.17-second simulated actuator lag','before_source':'cycle7_code/pilot.js','after_source':'cycle8_code/pilot.js'},'limits':['Live games are sequential, not matched A/B. Population and encounters vary.','Capped games are not deaths. Wall-clock cap and page-recorded seconds differ.','Kinematics replay drives recorded actual commands including future recorded commands for offline model identification. It is not online future knowledge or a survival counterfactual.','Lag 0.06 is local observed heading response on these sessions, not measured server RTT or guaranteed universal latency.','Synthetic tests are model checks, not real-game success rates.','Original 33F/73F raw state not retained; their exact counterfactual replay is unavailable. No claim of guaranteed survival.']}
(p/'progress2_source.txt').write_text('# V10 two-hour improvement: cycles 1–9 and held-out kinematics\n\n'+json.dumps(data,ensure_ascii=False,indent=2))
print(p/'progress2_source.txt')
