import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import zlib from 'node:zlib';import {performance} from 'node:perf_hooks';
const out='research/v111_20261001',d=JSON.parse(fs.readFileSync('params.json'));function load(path,clock=performance){const c=vm.createContext({performance:clock});vm.runInContext(fs.readFileSync(path,'utf8'),c);return c.SlpPilot;}
const {Pilot}=load('ext/pilot.js'),old=load(out+'/before/pilot.js'),V={...d.defaults,...d.presets.v111_near.values},before={...V,V111_ON:0};
for(const k of ['pilotStep','v8Step','v10Step','v10World','v9World','v10Route','v4Adv'])assert.equal(Pilot.prototype[k].toString(),old.Pilot.prototype[k].toString());
const base={x:30000,y:30000,ang:0,sp:6.12,sc:1,L:1000,t:10,cmdNow:0,boostNow:false,wall:[30000,30000,20000],segs:[],sid:[],heads:[],hid:[],food:[30200,30000,30],own:[]};
const a=new Pilot(V,'aggressive'),b=new old.Pilot(before,'aggressive');for(let i=0;i<12;i++){const s={...base,t:10+i*.1,v8Control:{phase:'feed',heads:0,radius:250,threshold:1,switched:i===0?1:0}};assert.equal(JSON.stringify(a.step(s)),JSON.stringify(b.step(s)));}assert.equal(a.v101Feed.values.V111_ON,0);
const p=new Pilot(V),ph=p.v4Physics(1),root={ok:false,st:{x:30000,y:30000,h:0,v:190},t:.063,pts:[]};
const W={check:(a,b)=>-3+Math.min(0,b.y-30000)*-.3};p.v111World=()=>W;const q=p.v111Local(base,W,ph,root,false);delete p.v111World;assert(q.recovery);assert(!q.ok);assert(q.angle<-.2);assert(q.evaluated>=.08);assert(q.pts.length>5);
// Worst static penetration must be invariant to observed wall order.
const wall={...base,segs:[30000,29900,30000,30100,20,30002,29900,30002,30100,30],sid:[1,2]};assert.equal(p.v111World(wall,true).check(root.st,root.st),p.v111World({...wall,segs:wall.segs.slice(5).concat(wall.segs.slice(0,5))},true).check(root.st,root.st));
const page=JSON.parse(fs.readFileSync(out+'/page_0.json')),frames=JSON.parse(zlib.gunzipSync(fs.readFileSync(out+'/page_0_box.json.gz'))).frames;
const replay=[];for(const f of frames.filter((f,i)=>f.t>page.record.seconds-1.2&&i%4===0)){const oa=new old.Pilot({...page.values,V101_ON:0,V11_ON:0},page.record.profile),nb=new Pilot({...page.values,V101_ON:0,V11_ON:0,V111_ON:1},page.record.profile);const prior=oa.step(f),after=nb.step(f);replay.push({t:f.t,before:prior,after,modeBefore:oa.last.trace.mode,modeAfter:nb.last.trace.mode,rootSafe:nb.last.trace.v10_root_safe,recovery:nb.last.trace.v111_recovery,depth:nb.last.trace.v111_depth,terminal:nb.last.trace.v111_terminal,evaluated:nb.last.trace.v111_evaluated_s,oldMs:oa.last.trace.v10_local_ms,newMs:nb.last.trace.v10_local_ms});}
assert(replay.length>0);assert(replay.some(q=>q.recovery));assert(replay.some(q=>Math.abs(q.after[0]-q.before[0])>.2));assert(replay.filter(q=>q.recovery).every(q=>q.modeAfter==='v10emergency'));
const result={originalFunctionsUnchanged:7,feedParityFrames:12,feedAlgorithmFlagOff:true,allFailedTurnsEvaluated:true,unsafeNotCertified:true,wallOrderIndependent:true,replay,limits:'fixed observations/model; no proven counterfactual survival'};fs.writeFileSync(out+'/check.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
