import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';import zlib from 'node:zlib';
const load=f=>{const c=vm.createContext({performance});vm.runInContext(fs.readFileSync(f,'utf8'),c);return c.SlpPilot;};
const api=load('ext/pilot.js'),old=load('research/b1_20261002/before/pilot.js'),D=JSON.parse(fs.readFileSync('params.json')),V={...D.defaults,...D.presets.b1_contour.values};
const preserved=['t6Step','t6World','t6Graph','t6GuideAt','t5Step','t4Step','v101Values','v101Step','v101WrapStep','v10Step','pilotStep','v8Step','v4Adv','v9World','v9Roll','v9Root'];for(const n of preserved)assert.equal(api.Pilot.prototype[n].toString(),old.Pilot.prototype[n].toString(),n);assert.equal(api.t5Contours.toString(),old.t5Contours.toString());assert.equal(api.v101Choice.toString(),old.v101Choice.toString());
const make=(parts=[],phase='feed')=>({x:30000,y:30000,ang:0,sp:5.8,sc:1,t:0,L:1000,wall:[30000,30000,20000],cmdNow:0,boostNow:false,segs:parts.flatMap(p=>[30000+p[0],30000+p[1],30000+p[2],30000+p[3],p[4]??20]),sid:parts.map((p,i)=>p[5]??i+1),heads:[],hid:[],food:[30900,30000,60,30910,30000,60],own:[],v8Control:{phase,heads:0,radius:450,threshold:3,switched:false}});
const plain=make(),oldV={...D.defaults,...D.presets.v101_hybrid.values},pa=new old.Pilot(oldV),pb=new api.Pilot(V);let openMatches=0;
for(let k=0;k<12;k++){const s={...plain,t:k*.1,food:[30900,30000+k*20,60,30910,30000+k*20,60]};const a=pa.step(s),b=pb.step(s);assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));assert.equal(pb.last.trace.b1_reason,'open_original');openMatches++;}
const curve=[];for(let k=0;k<96;k++){const a=k*Math.PI/48,b=(k+1)*Math.PI/48;if(Math.abs((a+b)/2-Math.PI/2)<.22)continue;curve.push([300*Math.cos(a),300*Math.sin(a),300*Math.cos(b),300*Math.sin(b),20,9]);}
const cases=[['food_parallel_lane',make([[-1000,-36,1000,-36,10],[-1000,36,1000,36,10]])],['food_front_wall',make([[140,-160,140,160,20]])],['avoid_u_reverse',make([[-220,-150,220,-150,15],[220,-150,220,150,15],[220,150,-220,150,15]],'avoid')],['avoid_narrow_gate',make([[180,-230,180,-26,10],[180,26,180,230,10],[-180,-230,180,-230,10],[-180,230,180,230,10],[-180,-230,-180,230,10]],'avoid')],['avoid_curved_enclosure',make(curve,'avoid')]];
const results=[];
for(const [name,initial] of cases){const p=new api.Pilot(V),s=structuredClone(initial),ph=p.v4Physics(s.sc),hist=[{t:-2,ang:0,boost:false}],origin={x:s.x,y:s.y};let minClear=Infinity,changed=0,maxRails=0,steps=0;const times=[];
 for(let k=0;k<120;k++){s.cmdHistory=hist.slice();s.cmdNow=hist.at(-1).ang;s.boostNow=hist.at(-1).boost;const started=performance.now(),[cmd,boost]=p.step(s);times.push(performance.now()-started);assert(Number.isFinite(cmd));changed+=p.last.trace.b1_intervened;maxRails=Math.max(maxRails,p.last.trace.b1_rail_count);const W=p.b1Fine.t6World(s);
  for(let j=0;j<4;j++){const t=s.t+j*.025,active=hist.findLast(q=>q.t<=t-V.TRACK_LAT)||hist[0],st={x:s.x,y:s.y,h:s.ang,v:s.sp*31},next=p.v4Adv(st,active.ang,active.boost,.025,ph),g=W.check(st,next,0,.025,0,false);minClear=Math.min(minClear,g);assert(g>=-.001,`${name}: collision ${g} at ${t}`);Object.assign(s,{x:next.x,y:next.y,ang:next.h,sp:next.v/31});}
  const quant=(Math.floor(((cmd%(2*Math.PI)+2*Math.PI)%(2*Math.PI))/(2*Math.PI)*251)+.5)*2*Math.PI/251;hist.push({t:s.t,ang:quant,boost});s.t+=.1;steps++;if(Math.hypot(s.x-origin.x,s.y-origin.y)>700)break;
 }
 const displacement=Math.hypot(s.x-origin.x,s.y-origin.y);times.sort((a,b)=>a-b);const r={name,steps,seconds:s.t,displacement,minClear,changed,maxRails,p50_ms:times[Math.floor(times.length*.5)],p95_ms:times[Math.floor(times.length*.95)]};results.push(r);console.log(r);assert(displacement>700,`${name}: no progress`);assert(maxRails>0);
}
// No route beyond a full body ring is advertised by the geometric graph.
const ring=[];for(let k=0;k<48;k++){const a=k*Math.PI/24,b=(k+1)*Math.PI/24;ring.push([170*Math.cos(a),170*Math.sin(a),170*Math.cos(b),170*Math.sin(b),20,9]);}const e=new api.Pilot(V);e.step(make(ring,'avoid'));assert.equal(e.last.trace.b1_graph_routes,0);
const unsafe=new api.Pilot(V);unsafe.step(make([[0,-500,0,500,20]],'avoid'));assert.equal(unsafe.last.draw.b1Unsafe,true);assert.equal(unsafe.last.trace.b1_reason,'recovery');
const q=new api.Pilot(V);q.step(make());q.setParams({...V,B1_GAP:0});assert.equal(q.b1Base,null);assert.equal(q.b1Fine,null);q.step(make());assert.equal(q.last.trace.b1_gap,0);
// Actual T6 death observations exercise production dispatch with current
// bodies, inputs, queued commands, and existing V10-1 switch logic.
const frames=JSON.parse(zlib.gunzipSync(fs.readFileSync('runs/t6_survival_20261002_141215/slp_04_box.json.gz'))).frames,replay=new api.Pilot(V);let replayN=0,replayInterventions=0;
for(const f of frames.filter((_,i)=>i%Math.ceil(frames.length/40)===0)){const s={...f};delete s.v8Control;const r=replay.step(s);assert(Number.isFinite(r[0]));assert.equal(replay.last.trace.b1_on,1);replayInterventions+=replay.last.trace.b1_intervened;replayN++;}
const result={old_methods_preserved:preserved.length,original_wrap_and_contours_preserved:true,open_food_command_matches:openMatches,closed_loop:results,unsafe_root_labelled:true,enclosed_no_false_exit:true,parameter_reset:true,recorded_observations:replayN,replay_interventions:replayInterventions,scope:'Local static-body delayed and quantized motion, plus recorded observation dispatch. No new live game or established survival/food improvement.'};fs.writeFileSync('research/b1_20261002/check.json',JSON.stringify(result,null,2));
