import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';import zlib from 'node:zlib';
const load=f=>{const c=vm.createContext({performance});vm.runInContext(fs.readFileSync(f,'utf8'),c);return c.SlpPilot;};
const api=load('ext/pilot.js'),old=load('research/b1_20261002/before/pilot.js'),D=JSON.parse(fs.readFileSync('params.json')),V={...D.defaults,...D.presets.b1_contour.values};
const preserved=['t6Step','t6World','t6Graph','t6GuideAt','t5Step','t4Step','v101Values','v101Step','v101WrapStep','v10Step','pilotStep','v8Step','v4Adv','v9World','v9Roll','v9Root'];for(const n of preserved)assert.equal(api.Pilot.prototype[n].toString(),old.Pilot.prototype[n].toString(),n);assert.equal(api.t5Contours.toString(),old.t5Contours.toString());assert.equal(api.v101Choice.toString(),old.v101Choice.toString());
const make=(parts=[],phase='feed')=>({x:30000,y:30000,ang:0,sp:5.8,sc:1,t:0,L:1000,wall:[30000,30000,20000],cmdNow:0,boostNow:false,segs:parts.flatMap(p=>[30000+p[0],30000+p[1],30000+p[2],30000+p[3],p[4]??20]),sid:parts.map((p,i)=>p[5]??i+1),heads:[],hid:[],food:[30900,30000,60,30910,30000,60],own:[],v8Control:{phase,heads:0,radius:450,threshold:3,switched:false}});
const plain=make(),oldV={...D.defaults,...D.presets.v101_hybrid.values},pa=new old.Pilot(oldV),pb=new api.Pilot(V);let openMatches=0;
for(let k=0;k<12;k++){const s={...plain,t:k*.1,food:[30900,30000+k*20,60,30910,30000+k*20,60]};const a=pa.step(s),b=pb.step(s);assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));assert.equal(pb.last.trace.b1_reason,'open_original');openMatches++;}
const curve=[];for(let k=0;k<96;k++){const a=k*Math.PI/48,b=(k+1)*Math.PI/48;if(Math.abs((a+b)/2-Math.PI/2)<.22)continue;curve.push([300*Math.cos(a),300*Math.sin(a),300*Math.cos(b),300*Math.sin(b),20,9]);}
const p=new api.Pilot(V),s=make(curve,'avoid'),h=[{t:-2,ang:0,boost:false}],ph=p.v4Physics(1);const rows=[];
for(let k=0;k<35;k++){s.cmdHistory=h.slice();s.cmdNow=h.at(-1).ang;s.boostNow=h.at(-1).boost;const [cmd,boost]=p.step(s);rows.push({t:s.t,x:s.x-30000,y:s.y-30000,cmd,boost,reason:p.last.trace.b1_reason,routes:p.last.trace.b1_graph_routes,graph:p.b1Fine.b1Graph?{reason:p.b1Fine.b1Graph.graph.reason,checks:p.b1Fine.b1Graph.graph.checks,nodes:p.b1Fine.b1Graph.graph.nodes,at:p.b1Fine.b1Graph.at}:null,goal:p.b1Fine.b1Goal});for(let j=0;j<4;j++){const t=s.t+j*.025,active=h.findLast(q=>q.t<=t-V.TRACK_LAT)||h[0],next=p.v4Adv({x:s.x,y:s.y,h:s.ang,v:s.sp*31},active.ang,active.boost,.025,ph);Object.assign(s,{x:next.x,y:next.y,ang:next.h,sp:next.v/31});}h.push({t:s.t,ang:cmd,boost});s.t+=.1;}
fs.writeFileSync('research/b1_20261002/curve_failure.json',JSON.stringify(rows,null,2));console.log(rows.map(x=>({t:x.t,x:x.x,y:x.y,routes:x.routes,reason:x.reason,graph:x.graph,goal:x.goal})));
