import json,base64,html
from pathlib import Path
root=Path('/home/datawave/Work_AI/슬리더'); out=root/'research/v10_objective_20261001'; run=root/'runs/v10_twenty_20261001_195831'
s=json.loads((out/'summary.json').read_text()); data=s['comparison']['results']
labels=['비상 수정 판 · 설정 혼합','전송 수정 중간 빌드 · 설정 고정','최신 빌드 1판 · 상한 종료','최신 빌드 2판 · 설정 혼합']
def chart(key,title,unit):
 maximum=max(r[m][key] for r in data for m in ['applied_input','actual_wire'])*1.15
 parts=[f'<h3>{title} <small>작을수록 좋음</small></h3><svg viewBox="0 0 740 350" role="img" aria-label="{title}">']
 for i,(r,label) in enumerate(zip(data,labels)):
  y=30+i*80;parts.append(f'<text x="8" y="{y}" fill="#cbd5e1" font-size="14">{label} · n={r["n"]}</text>')
  for j,m in enumerate(['applied_input','actual_wire']):
   v=r[m][key];w=v/maximum*470; yy=y+8+j*23;color=['#94a3b8','#38bdf8'][j]
   parts.append(f'<rect x="8" y="{yy}" width="{w:.2f}" height="17" rx="3" fill="{color}"/><text x="{w+17:.2f}" y="{yy+14}" fill="#f8fafc" font-size="13">{v:.2f}{unit}</text>')
 return ''.join(parts)+'</svg>'
cards=[]
for g in s['games']:
 k=g['game'];a=json.loads((run/f'analysis_{k:02}.json').read_text()); photo=base64.b64encode((run/a['photo']).read_bytes()).decode(); actual=(run/f'death_map_{k:02}.svg').read_text();alt=(run/f'improvement_{k:02}.svg').read_text()
 improve=g['improvement'].replace('모델 최소 간격 128.0px','모델 간격 지표 128.0px(계산 상한값)')
 cards.append(f'''<article id="game{k}"><h2>{k}판 · {'상한 종료 / 사망 아님' if g['capped'] else '사망 · 종료 시 V10'}</h2><p>게임 기록 {g['seconds']}초 · 최대 길이 {g['L_max']} · 설정 변경 {len(g['changes'])}건</p><p>{html.escape(g['cause'])}</p><details><summary>종료 직전 실제 촬영 화면 · 대응 시각 {a['photo_game_at']:.2f}초 (정확한 사망 순간은 아님)</summary><img alt="종료 직전 실제 촬영" src="data:image/jpeg;base64,{photo}"></details><div class="pair"><section><h3>실제 이동 · 좌표 재구성</h3>{actual}</section><section><h3>{'종료 구간 설명' if g['capped'] else '대안 움직임 · 생존 미입증'}</h3>{alt}</section></div><p>{html.escape(improve)}</p><p class="note">빨강: 실제 이동 / 청록: 모델 대안. 기록된 적의 미래를 고정한 재생이며 실제 탈출 성공을 입증하지 않습니다.</p></article>''')
rows=''.join(f'<tr><td>{labels[i]}</td><td>{r["n"]}</td><td>{r["changes"]}</td><td>{r["applied_input"]["wrong_turn_over_3deg"]} → {r["actual_wire"]["wrong_turn_over_3deg"]}</td></tr>' for i,r in enumerate(data))
h='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>V10 수정 효과 객관 분석</title><style>body{margin:0;background:#0b1220;color:#edf2f7;font:16px/1.65 system-ui}main{max-width:1100px;margin:auto;padding:24px}h1{font-size:28px}h2{font-size:21px}h3{font-size:17px}small,.note{color:#afbdd0}article,.panel{background:#162235;border:1px solid #29394f;border-radius:14px;padding:20px;margin:18px 0}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px}svg,img{display:block;width:100%;height:auto}a{color:#38bdf8}.badge{display:inline-block;padding:5px 12px;border-radius:9px;background:#243650;margin:4px}table{width:100%;border-collapse:collapse;font-size:14px}td,th{text-align:left;padding:10px 6px;border-bottom:1px solid #344256}summary{cursor:pointer}p{overflow-wrap:anywhere}.scroll{overflow-x:auto}button{background:#243650;color:#fff;border:1px solid #476080;border-radius:6px;padding:8px 14px;cursor:pointer}@media(max-width:700px){main{padding:12px}.pair{grid-template-columns:1fr}h1{font-size:23px}article,.panel{padding:14px}}@media print{body{background:white;color:black}article,.panel{break-inside:avoid;background:white}button{display:none}}</style></head><body><main><h1>V10 수정 효과 · 객관 분석</h1><p>2026-10-01 · 결론: <strong>전송 입력 불일치는 수정됐지만 생존·성장 개선은 입증되지 않았습니다.</strong></p><span class="badge">전송 결함: 수정 확인</span><span class="badge">예측 정확도: 일부 개선·일관성 부족</span><span class="badge">생존 효과: 판단 보류</span><p><a href="#compare">효과 비교</a> · <a href="#game1">1판</a> · <a href="#game2">2판</a> · <a href="#limits">검증 한계</a> <button onclick="window.print()">인쇄 / PDF</button></p><div class="panel" id="compare"><h2>같은 로그에서 50ms 뒤 예측 비교</h2><p>회색: 입력 갱신 이력 사용 / 파랑: 실제 전송 패킷 이력 사용. 기존 봇과 새 봇의 실게임 A/B 비교가 아닙니다.</p>'''
h+= '<div class="pair">'+chart('heading_mean_deg','평균 방향 예측 오차','°')+chart('heading_p95_deg','방향 예측 오차 P95','°')+'</div>'+chart('position_mean_px','평균 위치 예측 오차','px')
h+='<p>중간 빌드 판의 평균 방향 오차는 2.24° → 1.42°로 줄었습니다. 최신 고정 설정 판은 평균이 거의 같고 P95가 5.46° → 6.80°로 증가했습니다. 위치 오차 개선도 일관되지 않습니다.</p><div class="scroll"><table><thead><tr><th>관측 판</th><th>재생 표본</th><th>설정 변경</th><th>반대 회전 예측 (&gt;3°)</th></tr></thead><tbody>'+rows+'</tbody></table></div><p class="note">P95: 표본 95%가 이 값 이하인 오차. 표본은 같은 판의 연속 관측으로 독립 실험이 아닙니다.</p></div><div class="panel"><h2>수정별 판정</h2><p><strong>전송 모델:</strong> 로컬 검사 31개와 전송 패킷 대조로 구현 정합성을 확인했습니다. 실제 궤적 오차가 없어졌다는 뜻은 아닙니다.</p><p><strong>비상 회전:</strong> 회복 후보 평가는 작동했지만, 비상 판단이 발생한 판에서도 사망했습니다. 사망 예방 효과는 미입증입니다.</p><p><strong>다음 검토 방향:</strong> 막힌 뒤 비상 조향뿐 아니라 진입 전 출구 선택·통로 폐쇄 예측과 남은 지연·몸통 모델 오차를 살펴봐야 합니다.</p></div><h2>중지 전 수집된 2판 · 실제 화면과 대안 경로</h2><p>20판 계획은 사용자 중지로 2판에서 종료됐습니다. 1판은 수집 상한 종료, 2판은 사망입니다. 2판의 설정·V8/V10 전환 23건 때문에 전체 생존·성장을 V10 효과로 분리할 수 없습니다.</p>'+''.join(cards)
h+='''<div class="panel" id="limits"><h2>검증 범위와 한계</h2><ul><li>기존 로그의 마지막 약 60초를 사용한 오프라인 예측 비교입니다. 지연과 물리 모델은 근사입니다.</li><li>대조군 A/B, 충분한 독립 표본, 실제 대안 경로 주행 검증은 없습니다.</li><li>1판 게임 시계 654.1초와 수집기 상한 600초는 서로 다른 시계입니다. 사망으로 계산하지 않았습니다.</li><li>2판의 대안은 종료 약 2초 전 우회전·부스트 해제입니다. 모델상 침범은 없으나 128px 지표는 계산 상한이며 실제 생존 보장이 아닙니다.</li></ul><p>근거: .workspace/sources/v10-objective-effectiveness-20261001.md<br>비교 데이터: research/v10_objective_20261001/summary.json<br>판별 원자료: runs/v10_twenty_20261001_195831/</p></div></main></body></html>'''
(out/'report.html').write_text(h)
print(out/'report.html')
